services:
  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    restart: unless-stopped
    ports:
      - "11434:11434"
    volumes:
      - ./ollama_data:/root/.ollama
    command: ["sleep", "infinity"]

  postgres:
    image: postgres:latest
    container_name: chat_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: chat_history
    ports:
      - "5432:5432"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data

  chat:
    build: .
    container_name: llm_chat
    restart: always
    ports:
      - "8000:8000"
    environment:
      PGHOST: postgres
      PGPORT: 5432
      PGUSER: postgres
      PGPASSWORD: mypassword
      PGDB: chat_history
      OPENAI_API_KEY: api-key-ollama
      OPENAI_API_BASE: http://ollama:11434
      OPENAI_MODEL: llama3.2:3b
    depends_on:
      - ollama
      - postgres

  # adminer:
  #   image: adminer:latest
  #   container_name: adminer
  #   restart: always
  #   ports:
  #     - "8080:8080"
  #   depends_on:
  #     - postgres

volumes:
  ollama_data:
  postgres_data: