services:
  postgres:
    image: postgres:latest
    container_name: chat_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: chat_history
    ports:
      - "5432:5432"
    networks:
      - chat_network
    volumes:
      - ./postgres_data:/var/lib/postgresql/data

  chat:
    build: .
    container_name: llm_chat
    restart: always
    ports:
      - "8000:8000"
    environment:
      PGHOST: postgres
      PGPORT: 5432
      PGUSER: postgres
      PGPASSWORD: mypassword
      PGDB: chat_history
      OPENAI_API_KEY: sk-proj-...
      OPENAI_MODEL: gpt-4o-mini
    depends_on:
      - postgres
    networks:
      - chat_network

  # adminer:
  #   image: adminer:latest
  #   container_name: adminer
  #   restart: always
  #   ports:
  #     - "8080:8080"
  #   depends_on:
  #     - postgres

networks:
  chat_network:
    driver: bridge